import Exchange from './abstract/binance.js';
import type { Balances, Conversion, CrossBorrowRate, Currencies, Currency, FundingRateHistory, Greeks, Int, IsolatedBorrowRate, IsolatedBorrowRates, Leverage, Leverages, Liquidation, MarginMode, MarginModes, MarginModification, Market, MarketInterface, Num, OHLCV, OpenInterest, Option, Order, OrderBook, OrderRequest, OrderSide, OrderType, Str, Strings, Ticker, Tickers, Trade, TradingFeeInterface, TradingFees, Transaction, TransferEntry } from './base/types.js';
/**
 * @class binance
 * @augments Exchange
 */
export default class binance extends Exchange {
    describe(): any;
    isInverse(type: string, subType?: Str): boolean;
    isLinear(type: string, subType?: Str): boolean;
    setSandboxMode(enable: boolean): void;
    createExpiredOptionMarket(symbol: string): MarketInterface;
    market(symbol: string): MarketInterface;
    safeMarket(marketId?: Str, market?: Market, delimiter?: Str, marketType?: Str): MarketInterface;
    costToPrecision(symbol: any, cost: any): any;
    currencyToPrecision(code: any, fee: any, networkCode?: any): any;
    nonce(): number;
    fetchTime(params?: {}): Promise<number>;
    fetchCurrencies(params?: {}): Promise<Currencies>;
    fetchMarkets(params?: {}): Promise<Market[]>;
    parseMarket(market: any): Market;
    parseBalanceHelper(entry: any): import("./base/types.js").BalanceAccount;
    parseBalanceCustom(response: any, type?: any, marginMode?: any, isPortfolioMargin?: boolean): Balances;
    fetchBalance(params?: {}): Promise<Balances>;
    fetchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<OrderBook>;
    parseTicker(ticker: any, market?: Market): Ticker;
    fetchStatus(params?: {}): Promise<{
        status: string;
        updated: any;
        eta: any;
        url: any;
        info: any;
    }>;
    fetchTicker(symbol: string, params?: {}): Promise<Ticker>;
    fetchBidsAsks(symbols?: Strings, params?: {}): Promise<import("./base/types.js").Dictionary<Ticker>>;
    fetchLastPrices(symbols?: Strings, params?: {}): Promise<import("./base/types.js").LastPrices>;
    parseLastPrice(entry: any, market?: Market): {
        datetime: string;
        info: any;
        price: number;
        side: any;
        symbol: string;
        timestamp: number;
    };
    fetchTickers(symbols?: Strings, params?: {}): Promise<Tickers>;
    parseOHLCV(ohlcv: any, market?: Market): OHLCV;
    fetchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    parseTrade(trade: any, market?: Market): Trade;
    fetchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    editSpotOrder(id: string, symbol: string, type: OrderType, side: OrderSide, amount: number, price?: Num, params?: {}): Promise<Order>;
    editSpotOrderRequest(id: string, symbol: string, type: OrderType, side: OrderSide, amount: number, price?: Num, params?: {}): any;
    editContractOrderRequest(id: string, symbol: string, type: OrderType, side: OrderSide, amount: number, price?: Num, params?: {}): {
        symbol: string;
        side: string;
    };
    editContractOrder(id: string, symbol: string, type: OrderType, side: OrderSide, amount: number, price?: Num, params?: {}): Promise<Order>;
    editOrder(id: string, symbol: string, type: OrderType, side: OrderSide, amount?: Num, price?: Num, params?: {}): Promise<Order>;
    parseOrderStatus(status: any): string;
    parseOrder(order: any, market?: Market): Order;
    createOrders(orders: OrderRequest[], params?: {}): Promise<Order[]>;
    createOrder(symbol: string, type: OrderType, side: OrderSide, amount: number, price?: Num, params?: {}): Promise<Order>;
    createOrderRequest(symbol: string, type: OrderType, side: OrderSide, amount: number, price?: Num, params?: {}): any;
    createMarketOrderWithCost(symbol: string, side: OrderSide, cost: number, params?: {}): Promise<Order>;
    createMarketBuyOrderWithCost(symbol: string, cost: number, params?: {}): Promise<Order>;
    createMarketSellOrderWithCost(symbol: string, cost: number, params?: {}): Promise<Order>;
    fetchOrder(id: string, symbol?: Str, params?: {}): Promise<Order>;
    fetchOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchOpenOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchOpenOrder(id: string, symbol?: Str, params?: {}): Promise<Order>;
    fetchClosedOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchCanceledOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchCanceledAndClosedOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    cancelOrder(id: string, symbol?: Str, params?: {}): Promise<Order>;
    cancelAllOrders(symbol?: Str, params?: {}): Promise<any>;
    cancelOrders(ids: string[], symbol?: Str, params?: {}): Promise<Order[]>;
    fetchOrderTrades(id: string, symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchMyTrades(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchMyDustTrades(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseDustTrade(trade: any, market?: Market): {
        amount: number;
        cost: number;
        datetime: string;
        fee: {
            currency: any;
            cost: number;
        };
        id: any;
        info: any;
        order: string;
        price: number;
        side: any;
        symbol: any;
        takerOrMaker: any;
        timestamp: number;
        type: any;
    };
    fetchDeposits(code?: Str, since?: Int, limit?: Int, params?: {}): Promise<Transaction[]>;
    fetchWithdrawals(code?: Str, since?: Int, limit?: Int, params?: {}): Promise<Transaction[]>;
    parseTransactionStatusByType(status: any, type?: any): string;
    parseTransaction(transaction: any, currency?: Currency): Transaction;
    parseTransferStatus(status: any): string;
    parseTransfer(transfer: any, currency?: Currency): {
        amount: number;
        currency: string;
        datetime: string;
        fromAccount: any;
        id: string;
        info: any;
        status: string;
        timestamp: number;
        toAccount: any;
    };
    parseIncome(income: any, market?: Market): {
        info: any;
        symbol: string;
        code: string;
        timestamp: number;
        datetime: string;
        id: string;
        amount: number;
    };
    transfer(code: string, amount: number, fromAccount: string, toAccount: string, params?: {}): Promise<TransferEntry>;
    fetchTransfers(code?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchDepositAddress(code: string, params?: {}): Promise<{
        address: string;
        currency: string;
        info: any;
        network: any;
        tag: string;
    }>;
    fetchTransactionFees(codes?: string[], params?: {}): Promise<{
        withdraw: {};
        deposit: {};
        info: any;
    }>;
    fetchDepositWithdrawFees(codes?: Strings, params?: {}): Promise<any>;
    parseDepositWithdrawFee(fee: any, currency?: Currency): any;
    withdraw(code: string, amount: number, address: string, tag?: any, params?: {}): Promise<Transaction>;
    parseTradingFee(fee: any, market?: Market): TradingFeeInterface;
    fetchTradingFee(symbol: string, params?: {}): Promise<TradingFeeInterface>;
    fetchTradingFees(params?: {}): Promise<TradingFees>;
    futuresTransfer(code: string, amount: any, type: any, params?: {}): Promise<{
        amount: number;
        currency: string;
        datetime: string;
        fromAccount: any;
        id: string;
        info: any;
        status: string;
        timestamp: number;
        toAccount: any;
    }>;
    fetchFundingRate(symbol: string, params?: {}): Promise<{
        datetime: string;
        estimatedSettlePrice: number;
        fundingDatetime: string;
        fundingRate: number;
        fundingTimestamp: number;
        indexPrice: number;
        info: any;
        interestRate: number;
        markPrice: number;
        nextFundingDatetime: any;
        nextFundingRate: any;
        nextFundingTimestamp: any;
        previousFundingDatetime: any;
        previousFundingRate: any;
        previousFundingTimestamp: any;
        symbol: string;
        timestamp: number;
    }>;
    fetchFundingRateHistory(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<FundingRateHistory[]>;
    fetchFundingRates(symbols?: Strings, params?: {}): Promise<any>;
    parseFundingRate(contract: any, market?: Market): {
        datetime: string;
        estimatedSettlePrice: number;
        fundingDatetime: string;
        fundingRate: number;
        fundingTimestamp: number;
        indexPrice: number;
        info: any;
        interestRate: number;
        markPrice: number;
        nextFundingDatetime: any;
        nextFundingRate: any;
        nextFundingTimestamp: any;
        previousFundingDatetime: any;
        previousFundingRate: any;
        previousFundingTimestamp: any;
        symbol: string;
        timestamp: number;
    };
    parseAccountPositions(account: any, filterClosed?: boolean): any[];
    parseAccountPosition(position: any, market?: Market): {
        collateral: number;
        contracts: number;
        contractSize: any;
        datetime: string;
        entryPrice: number;
        hedged: boolean;
        id: any;
        info: any;
        initialMargin: number;
        initialMarginPercentage: number;
        leverage: number;
        liquidationPrice: any;
        maintenanceMargin: number;
        maintenanceMarginPercentage: number;
        marginMode: any;
        marginRatio: any;
        markPrice: any;
        notional: number;
        percentage: any;
        side: any;
        symbol: string;
        timestamp: number;
        unrealizedPnl: number;
    };
    parsePositionRisk(position: any, market?: Market): {
        collateral: number;
        contractSize: any;
        contracts: number;
        datetime: string;
        entryPrice: number;
        hedged: boolean;
        id: any;
        info: any;
        initialMargin: number;
        initialMarginPercentage: number;
        leverage: number;
        liquidationPrice: number;
        maintenanceMargin: number;
        maintenanceMarginPercentage: number;
        marginMode: string;
        marginRatio: any;
        marginType: string;
        markPrice: number;
        notional: number;
        percentage: any;
        side: any;
        stopLossPrice: any;
        symbol: string;
        takeProfitPrice: any;
        timestamp: number;
        unrealizedPnl: number;
    };
    loadLeverageBrackets(reload?: boolean, params?: {}): Promise<any>;
    fetchLeverageTiers(symbols?: Strings, params?: {}): Promise<{}>;
    parseMarketLeverageTiers(info: any, market?: Market): any[];
    fetchPosition(symbol: string, params?: {}): Promise<import("./base/types.js").Position>;
    fetchOptionPositions(symbols?: Strings, params?: {}): Promise<import("./base/types.js").Position[]>;
    parsePosition(position: any, market?: Market): import("./base/types.js").Position;
    fetchPositions(symbols?: Strings, params?: {}): Promise<import("./base/types.js").Position[]>;
    fetchAccountPositions(symbols?: Strings, params?: {}): Promise<import("./base/types.js").Position[]>;
    fetchPositionsRisk(symbols?: Strings, params?: {}): Promise<import("./base/types.js").Position[]>;
    fetchFundingHistory(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<import("./base/types.js").FundingHistory[]>;
    setLeverage(leverage: Int, symbol?: Str, params?: {}): Promise<any>;
    setMarginMode(marginMode: string, symbol?: Str, params?: {}): Promise<any>;
    setPositionMode(hedged: boolean, symbol?: Str, params?: {}): Promise<any>;
    fetchLeverages(symbols?: string[], params?: {}): Promise<Leverages>;
    parseLeverage(leverage: any, market?: any): Leverage;
    fetchSettlementHistory(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchMySettlementHistory(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseSettlement(settlement: any, market: any): {
        info: any;
        symbol: string;
        price: number;
        timestamp: number;
        datetime: string;
    };
    parseSettlements(settlements: any, market: any): any[];
    fetchLedgerEntry(id: string, code?: Str, params?: {}): Promise<any>;
    fetchLedger(code?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseLedgerEntry(item: any, currency?: Currency): {
        account: any;
        after: any;
        amount: number;
        before: any;
        currency: string;
        datetime: string;
        direction: any;
        fee: any;
        id: string;
        info: any;
        referenceAccount: any;
        referenceId: string;
        status: any;
        timestamp: number;
        type: string;
    };
    parseLedgerEntryType(type: any): string;
    sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any): {
        url: any;
        method: string;
        body: any;
        headers: any;
    };
    getExceptionsByUrl(url: any, exactOrBroad: any): import("./base/types.js").Dictionary<any>;
    handleErrors(code: any, reason: any, url: any, method: any, headers: any, body: any, response: any, requestHeaders: any, requestBody: any): any;
    calculateRateLimiterCost(api: any, method: any, path: any, params: any, config?: {}): any;
    request(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any, config?: {}): Promise<any>;
    modifyMarginHelper(symbol: string, amount: any, addOrReduce: any, params?: {}): Promise<any>;
    parseMarginModification(data: any, market?: Market): MarginModification;
    reduceMargin(symbol: string, amount: number, params?: {}): Promise<MarginModification>;
    addMargin(symbol: string, amount: number, params?: {}): Promise<MarginModification>;
    fetchCrossBorrowRate(code: string, params?: {}): Promise<CrossBorrowRate>;
    fetchIsolatedBorrowRate(symbol: string, params?: {}): Promise<IsolatedBorrowRate>;
    fetchIsolatedBorrowRates(params?: {}): Promise<IsolatedBorrowRates>;
    fetchBorrowRateHistory(code: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseBorrowRateHistory(response: any, code: any, since: any, limit: any): any;
    parseBorrowRate(info: any, currency?: Currency): {
        currency: string;
        datetime: string;
        info: any;
        period: number;
        rate: number;
        timestamp: number;
    };
    parseIsolatedBorrowRate(info: any, market?: Market): {
        info: any;
        symbol: string;
        base: string;
        baseRate: number;
        quote: string;
        quoteRate: number;
        period: number;
        timestamp: any;
        datetime: any;
    };
    createGiftCode(code: string, amount: any, params?: {}): Promise<{
        amount: any;
        code: string;
        currency: string;
        id: string;
        info: any;
    }>;
    redeemGiftCode(giftcardCode: any, params?: {}): Promise<any>;
    verifyGiftCode(id: string, params?: {}): Promise<any>;
    fetchBorrowInterest(code?: Str, symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseBorrowInterest(info: any, market?: Market): {
        account: string;
        amountBorrowed: number;
        currency: string;
        datetime: string;
        info: any;
        interest: number;
        interestRate: number;
        marginMode: string;
        symbol: string;
        timestamp: number;
    };
    repayCrossMargin(code: string, amount: any, params?: {}): Promise<{
        amount: any;
        currency: string;
        datetime: any;
        id: number;
        info: any;
        symbol: any;
        timestamp: any;
    }>;
    repayIsolatedMargin(symbol: string, code: string, amount: any, params?: {}): Promise<{
        amount: any;
        currency: string;
        datetime: any;
        id: number;
        info: any;
        symbol: any;
        timestamp: any;
    }>;
    borrowCrossMargin(code: string, amount: number, params?: {}): Promise<{
        amount: any;
        currency: string;
        datetime: any;
        id: number;
        info: any;
        symbol: any;
        timestamp: any;
    }>;
    borrowIsolatedMargin(symbol: string, code: string, amount: number, params?: {}): Promise<{
        amount: any;
        currency: string;
        datetime: any;
        id: number;
        info: any;
        symbol: any;
        timestamp: any;
    }>;
    parseMarginLoan(info: any, currency?: Currency): {
        amount: any;
        currency: string;
        datetime: any;
        id: number;
        info: any;
        symbol: any;
        timestamp: any;
    };
    fetchOpenInterestHistory(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OpenInterest[]>;
    fetchOpenInterest(symbol: string, params?: {}): Promise<OpenInterest>;
    parseOpenInterest(interest: any, market?: Market): OpenInterest;
    fetchMyLiquidations(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Liquidation[]>;
    parseLiquidation(liquidation: any, market?: Market): Liquidation;
    fetchGreeks(symbol: string, params?: {}): Promise<Greeks>;
    parseGreeks(greeks: any, market?: Market): {
        askImpliedVolatility: number;
        askPrice: any;
        askSize: any;
        bidImpliedVolatility: number;
        bidPrice: any;
        bidSize: any;
        datetime: any;
        delta: number;
        gamma: number;
        info: any;
        lastPrice: any;
        markImpliedVolatility: number;
        markPrice: number;
        rho: any;
        symbol: string;
        theta: number;
        timestamp: any;
        underlyingPrice: any;
        vega: number;
    };
    fetchTradingLimits(symbols?: Strings, params?: {}): Promise<{}>;
    fetchPositionMode(symbol?: Str, params?: {}): Promise<{
        hedged: boolean;
        info: any;
    }>;
    fetchMarginModes(symbols?: string[], params?: {}): Promise<MarginModes>;
    parseMarginMode(marginMode: any, market?: any): MarginMode;
    fetchOption(symbol: string, params?: {}): Promise<Option>;
    parseOption(chain: any, currency?: Currency, market?: Market): {
        askPrice: number;
        baseVolume: number;
        bidPrice: number;
        change: number;
        currency: any;
        datetime: any;
        impliedVolatility: any;
        info: any;
        lastPrice: number;
        markPrice: any;
        midPrice: any;
        openInterest: any;
        percentage: number;
        quoteVolume: any;
        symbol: string;
        timestamp: any;
        underlyingPrice: number;
    };
    fetchMarginAdjustmentHistory(symbol?: Str, type?: Str, since?: Num, limit?: Num, params?: {}): Promise<MarginModification[]>;
    fetchConvertCurrencies(params?: {}): Promise<Currencies>;
    fetchConvertQuote(fromCode: string, toCode: string, amount?: Num, params?: {}): Promise<Conversion>;
    createConvertTrade(id: string, fromCode: string, toCode: string, amount?: Num, params?: {}): Promise<Conversion>;
    fetchConvertTrade(id: string, code?: Str, params?: {}): Promise<Conversion>;
    fetchConvertTradeHistory(code?: Str, since?: Int, limit?: Int, params?: {}): Promise<Conversion[]>;
    parseConversion(conversion: any, fromCurrency?: Currency, toCurrency?: Currency): Conversion;
}
