import Exchange from './abstract/cex.js';
import { Int, OrderSide } from './base/types.js';
export default class cex extends Exchange {
    describe(): any;
    fetchCurrenciesFromCache(params?: {}): Promise<any>;
    fetchCurrencies(params?: {}): Promise<{}>;
    fetchMarkets(params?: {}): Promise<any[]>;
    parseBalance(response: any): any;
    fetchBalance(params?: {}): Promise<any>;
    fetchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    parseOHLCV(ohlcv: any, market?: any): any[];
    fetchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseTicker(ticker: any, market?: any): any;
    fetchTickers(symbols?: string[], params?: {}): Promise<any>;
    fetchTicker(symbol: string, params?: {}): Promise<any>;
    parseTrade(trade: any, market?: any): any;
    fetchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchTradingFees(params?: {}): Promise<{}>;
    createOrder(symbol: string, type: any, side: OrderSide, amount: any, price?: any, params?: {}): Promise<{
        id: any;
        info: any;
        clientOrderId: any;
        timestamp: any;
        datetime: any;
        lastTradeTimestamp: any;
        type: any;
        side: any;
        symbol: any;
        status: string;
        price: any;
        amount: any;
        cost: any;
        average: any;
        remaining: any;
        filled: any;
        fee: any;
        trades: any;
    }>;
    cancelOrder(id: string, symbol?: string, params?: {}): Promise<any>;
    parseOrder(order: any, market?: any): {
        id: any;
        clientOrderId: any;
        datetime: any;
        timestamp: any;
        lastTradeTimestamp: any;
        status: any;
        symbol: any;
        type: string;
        timeInForce: any;
        postOnly: any;
        side: any;
        price: any;
        stopPrice: any;
        triggerPrice: any;
        cost: any;
        amount: any;
        filled: number;
        remaining: any;
        trades: any;
        fee: any;
        info: any;
        average: any;
    };
    fetchOpenOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchClosedOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchOrder(id: string, symbol?: string, params?: {}): Promise<{
        id: any;
        clientOrderId: any;
        datetime: any;
        timestamp: any;
        lastTradeTimestamp: any;
        status: any;
        symbol: any;
        type: string;
        timeInForce: any;
        postOnly: any;
        side: any;
        price: any;
        stopPrice: any;
        triggerPrice: any;
        cost: any;
        amount: any;
        filled: number;
        remaining: any;
        trades: any;
        fee: any;
        info: any;
        average: any;
    }>;
    fetchOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any[]>;
    parseOrderStatus(status: any): any;
    editOrder(id: string, symbol: any, type: any, side: any, amount?: any, price?: any, params?: {}): Promise<{
        id: any;
        clientOrderId: any;
        datetime: any;
        timestamp: any;
        lastTradeTimestamp: any;
        status: any;
        symbol: any;
        type: string;
        timeInForce: any;
        postOnly: any;
        side: any;
        price: any;
        stopPrice: any;
        triggerPrice: any;
        cost: any;
        amount: any;
        filled: number;
        remaining: any;
        trades: any;
        fee: any;
        info: any;
        average: any;
    }>;
    fetchDepositAddress(code: string, params?: {}): Promise<{
        currency: string;
        address: any;
        tag: any;
        network: any;
        info: any;
    }>;
    nonce(): any;
    sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any): {
        url: string;
        method: string;
        body: any;
        headers: any;
    };
    handleErrors(code: any, reason: any, url: any, method: any, headers: any, body: any, response: any, requestHeaders: any, requestBody: any): any[];
}
