import Exchange from './abstract/coinbase.js';
import { Int, OrderSide } from './base/types.js';
export default class coinbase extends Exchange {
    describe(): any;
    fetchTime(params?: {}): Promise<any>;
    fetchAccounts(params?: {}): Promise<any>;
    fetchAccountsV2(params?: {}): Promise<any>;
    fetchAccountsV3(params?: {}): Promise<any>;
    parseAccount(account: any): {
        id: any;
        type: any;
        code: any;
        info: any;
    };
    createDepositAddress(code: string, params?: {}): Promise<{
        currency: string;
        tag: any;
        address: any;
        info: any;
    }>;
    fetchMySells(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchMyBuys(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchTransactionsWithMethod(method: any, code?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchWithdrawals(code?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchDeposits(code?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseTransactionStatus(status: any): any;
    parseTransaction(transaction: any, market?: any): {
        info: any;
        id: any;
        txid: any;
        timestamp: any;
        datetime: any;
        network: any;
        address: any;
        addressTo: any;
        addressFrom: any;
        tag: any;
        tagTo: any;
        tagFrom: any;
        type: any;
        amount: any;
        currency: any;
        status: any;
        updated: any;
        fee: {
            cost: any;
            currency: any;
        };
    };
    parseTrade(trade: any, market?: any): any;
    fetchMarkets(params?: {}): Promise<any>;
    fetchMarketsV2(params?: {}): Promise<any[]>;
    fetchMarketsV3(params?: {}): Promise<any[]>;
    fetchCurrenciesFromCache(params?: {}): Promise<any>;
    fetchCurrencies(params?: {}): Promise<{}>;
    fetchTickers(symbols?: string[], params?: {}): Promise<any>;
    fetchTickersV2(symbols?: string[], params?: {}): Promise<any>;
    fetchTickersV3(symbols?: string[], params?: {}): Promise<any>;
    fetchTicker(symbol: string, params?: {}): Promise<any>;
    fetchTickerV2(symbol: string, params?: {}): Promise<any>;
    fetchTickerV3(symbol: string, params?: {}): Promise<any>;
    parseTicker(ticker: any, market?: any): any;
    parseBalance(response: any, params?: {}): any;
    fetchBalance(params?: {}): Promise<any>;
    fetchLedger(code?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseLedgerEntryStatus(status: any): any;
    parseLedgerEntryType(type: any): any;
    parseLedgerEntry(item: any, currency?: any): {
        info: any;
        id: any;
        timestamp: any;
        datetime: any;
        direction: any;
        account: any;
        referenceId: any;
        referenceAccount: any;
        type: any;
        currency: any;
        amount: any;
        before: any;
        after: any;
        status: any;
        fee: any;
    };
    findAccountId(code: any): Promise<any>;
    prepareAccountRequest(limit?: Int, params?: {}): {
        account_id: any;
    };
    prepareAccountRequestWithCurrencyCode(code?: string, limit?: Int, params?: {}): Promise<{
        account_id: any;
    }>;
    createOrder(symbol: string, type: any, side: OrderSide, amount: any, price?: any, params?: {}): Promise<any>;
    parseOrder(order: any, market?: any): any;
    parseOrderStatus(status: any): any;
    parseOrderType(type: any): any;
    parseTimeInForce(timeInForce: any): any;
    cancelOrder(id: string, symbol?: string, params?: {}): Promise<any>;
    cancelOrders(ids: any, symbol?: string, params?: {}): Promise<any>;
    fetchOrder(id: string, symbol?: string, params?: {}): Promise<any>;
    fetchOrders(symbol?: string, since?: Int, limit?: number, params?: {}): Promise<any>;
    fetchOrdersByStatus(status: any, symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchOpenOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchClosedOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchCanceledOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    parseOHLCV(ohlcv: any, market?: any): any[];
    fetchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchMyTrades(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    sign(path: any, api?: any[], method?: string, params?: {}, headers?: any, body?: any): {
        url: string;
        method: string;
        body: any;
        headers: any;
    };
    handleErrors(code: any, reason: any, url: any, method: any, headers: any, body: any, response: any, requestHeaders: any, requestBody: any): any;
}
