# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.pro.binance import binance
from ccxt.base.types import Any

import ccxt.async_support.binanceus as binanceusRest


class binanceus(binance):

    def describe(self) -> Any:
        # eslint-disable-next-line new-cap
        restInstance = binanceusRest()
        restDescribe = restInstance.describe()
        parentWsDescribe = super(binanceus, self).describe_data()
        extended = self.deep_extend(restDescribe, parentWsDescribe)
        return self.deep_extend(extended, {
            'certified': False,
            'countries': ['US'],
            'fees': {
                'trading': {
                    'maker': 0.0,  # 0.1% trading fee, zero fees for all trading pairs before November 1
                    'percentage': True,
                    'taker': 0.0,  # 0.1% trading fee, zero fees for all trading pairs before November 1
                    'tierBased': False,
                },
            },  # US
            'id': 'binanceus',
            'name': 'Binance US',
            'options': {
                'defaultType': 'spot',
                'fetchCurrencies': False,
                'fetchMarkets': ['spot'],
                'quoteOrderQty': False,
            },
            'urls': {
                'api': {
                    'private': 'https://api.binance.us/api/v3',
                    'public': 'https://api.binance.us/api/v3',
                    'sapi': 'https://api.binance.us/sapi/v1',
                    'v1': 'https://api.binance.us/api/v1',
                    'v3': 'https://api.binance.us/api/v3',
                    'wapi': 'https://api.binance.us/wapi/v3',
                    'web': 'https://www.binance.us',
                    'ws': {
                        'spot': 'wss://stream.binance.us:9443/ws',
                    },
                },
                'doc': 'https://github.com/binance-us/binance-official-api-docs',
                'fees': 'https://www.binance.us/en/fee/schedule',
                'logo': 'https://user-images.githubusercontent.com/1294454/65177307-217b7c80-da5f-11e9-876e-0b748ba0a358.jpg',
                'referral': 'https://www.binance.us/?ref=35005074',
                'www': 'https://www.binance.us',
            },
        })
