import coinbaseproRest from '../coinbasepro.js';
import { Int } from '../base/types.js';
import Client from '../base/ws/Client.js';
export default class coinbasepro extends coinbaseproRest {
    describe(): any;
    authenticate(): {
        timestamp: any;
        key: any;
        signature: any;
        passphrase: any;
    };
    subscribe(name: any, symbol: any, messageHashStart: any, params?: {}): Promise<any>;
    watchTicker(symbol: string, params?: {}): Promise<any>;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    watchMyTrades(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    watchOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    handleTrade(client: Client, message: any): any;
    handleMyTrade(client: Client, message: any): any;
    parseWsTrade(trade: any): any;
    parseWsOrderStatus(status: any): any;
    handleOrder(client: Client, message: any): void;
    parseWsOrder(order: any): {
        info: any;
        symbol: any;
        id: any;
        clientOrderId: any;
        timestamp: any;
        datetime: any;
        lastTradeTimestamp: any;
        type: any;
        timeInForce: any;
        postOnly: any;
        side: any;
        price: any;
        stopPrice: any;
        triggerPrice: any;
        amount: any;
        cost: any;
        average: any;
        filled: any;
        remaining: any;
        status: any;
        fee: any;
        trades: any;
    };
    handleTicker(client: Client, message: any): any;
    parseTicker(ticker: any, market?: any): any;
    handleDelta(bookside: any, delta: any): void;
    handleDeltas(bookside: any, deltas: any): void;
    handleOrderBook(client: Client, message: any): void;
    handleSubscriptionStatus(client: Client, message: any): any;
    handleErrorMessage(client: Client, message: any): boolean;
    handleMessage(client: Client, message: any): any;
}
