<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\binanceus as binance;

class binanceus extends binance {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'api' => array(
                'private' => array(
                    'delete' => array(
                        'order' => 1,
                        'openOrders' => 1,
                        'orderList' => 1,
                    ),
                    'get' => array(
                        'account' => 10,
                        'allOrderList' => 10,
                        'allOrders' => 10,
                        'myPreventedMatches' => 10, // with ID it has weight 1, but we don't have that complex handling yet
                        'myTrades' => 10,
                        'openOrderList' => 3,
                        'openOrders' => array( 'cost' => 3, 'noSymbol' => 40 ),
                        'order' => 2,
                        'orderList' => 2,
                        'rateLimit/order' => 20,
                    ),
                    'post' => array(
                        'order' => 1,
                        'order/cancelReplace' => 1,
                        'order/oco' => 1,
                        'order/test' => 1,
                    ),
                ),
                'public' => array(
                    'get' => array(
                        'aggTrades' => 1,
                        'avgPrice' => 1,
                        'depth' => array( 'cost' => 1, 'byLimit' => array( array( 100, 1 ), array( 500, 5 ), array( 1000, 10 ), array( 5000, 50 ) ) ),
                        'exchangeInfo' => 10,
                        'historicalTrades' => 5,
                        'klines' => 1,
                        'ping' => 1,
                        'ticker' => array( 'cost' => 2, 'noSymbol' => 100 ),
                        'ticker/24hr' => array( 'cost' => 1, 'noSymbol' => 40 ),
                        'ticker/bookTicker' => array( 'cost' => 1, 'noSymbol' => 2 ),
                        'ticker/price' => array( 'cost' => 1, 'noSymbol' => 2 ),
                        'time' => 1,
                        'trades' => 1,
                    ),
                ),
                'sapi' => array(
                    'delete' => array(
                        'custodian/cancelOcoOrder' => 1,
                        'custodian/cancelOrder' => 1,
                        'custodian/cancelOrdersBySymbol' => 1,
                    ),
                    'get' => array(
                        'apipartner/checkEligibility' => 1,
                        'apipartner/rebateHistory' => 1,
                        'asset/assetDistributionHistory' => 1,
                        'asset/query/dust-assets' => 1,
                        'asset/query/dust-logs' => 1,
                        'asset/query/trading-fee' => 1,
                        'asset/query/trading-volume' => 1,
                        'capital/config/getall' => 1,
                        'capital/deposit/address' => 1,
                        'capital/deposit/hisrec' => 1,
                        'capital/sub-account/deposit/address' => 1,
                        'capital/sub-account/deposit/history' => 1,
                        'capital/withdraw/history' => 1,
                        'cl/transferHistory' => 1,
                        'custodian/balance' => 1,
                        'custodian/custodianTransferHistory' => 1,
                        'custodian/openOrders' => 1,
                        'custodian/order' => 1,
                        'custodian/orderHistory' => 1,
                        'custodian/settlementHistory' => 1,
                        'custodian/settlementSetting' => 1,
                        'custodian/supportedAssetList' => 1,
                        'custodian/tradeHistory' => 1,
                        'custodian/walletTransferHistory' => 1,
                        'fiatpayment/query/deposit/history' => 1,
                        'fiatpayment/query/withdraw/history' => 1,
                        'marketing/referral/reward/history' => 1,
                        'ocbs/orders' => 1,
                        'otc/coinPairs' => 1,
                        'otc/orders' => 1,
                        'otc/orders/{orderId}' => 1,
                        'staking/asset' => 1,
                        'staking/history' => 1,
                        'staking/stakingBalance' => 1,
                        'staking/stakingRewardsHistory' => 1,
                        'sub-account/spotSummary' => 1,
                        'sub-account/status' => 1,
                        'system/status' => 1,
                    ),
                    'post' => array(
                        'asset/dust' => 10,
                        'capital/withdraw/apply' => 1,
                        'cl/transfer' => 1,
                        'custodian/custodianTransfer' => 1,
                        'custodian/ocoOrder' => 1,
                        'custodian/order' => 1,
                        'custodian/undoTransfer' => 1,
                        'custodian/walletTransfer' => 1,
                        'fiatpayment/withdraw/apply' => 1,
                        'otc/orders' => 1,
                        'otc/quotes' => 1,
                        'staking/stake' => 1,
                        'staking/unstake' => 1,
                    ),
                ),
                'sapiV2' => array(
                    'get' => array(
                        'cl/account' => 10,
                        'cl/alertHistory' => 1,
                    ),
                ),
                'sapiV3' => array(
                    'get' => array(
                        'accountStatus' => 1,
                        'apiTradingStatus' => 1,
                        'sub-account/assets' => 1,
                        'sub-account/list' => 1,
                        'sub-account/transfer/history' => 1,
                    ),
                    'post' => array(
                        'sub-account/transfer' => 1,
                    ),
                ),
            ),
            'certified' => false,
            'countries' => array( 'US' ), // US
            'fees' => array(
                'trading' => array(
                    'maker' => $this->parse_number('0.001'), // 0.1% trading fee, zero fees for all trading pairs before November 1.
                    'percentage' => true,
                    'taker' => $this->parse_number('0.001'), // 0.1% trading fee, zero fees for all trading pairs before November 1.
                    'tierBased' => true,
                ),
            ),
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => null,
                'option' => false,
                'addMargin' => false,
                'closeAllPositions' => false,
                'closePosition' => false,
                'createReduceOnlyOrder' => false,
                'fetchBorrowInterest' => false,
                'fetchBorrowRate' => false,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchBorrowRates' => false,
                'fetchBorrowRatesPerSymbol' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedPositions' => false,
                'fetchLeverage' => false,
                'fetchLeverageTiers' => false,
                'fetchMarketLeverageTiers' => false,
                'fetchMarkOHLCV' => false,
                'fetchOpenInterestHistory' => false,
                'fetchPosition' => false,
                'fetchPositions' => false,
                'fetchPositionsRisk' => false,
                'fetchPremiumIndexOHLCV' => false,
                'reduceMargin' => false,
                'setLeverage' => false,
                'setMargin' => false,
                'setMarginMode' => false,
                'setPositionMode' => false,
            ),
            'hostname' => 'binance.us',
            'id' => 'binanceus',
            'name' => 'Binance US',
            'options' => array(
                'fetchMargins' => false,
                'fetchMarkets' => array( 'spot' ),
                'defaultType' => 'spot',
                'quoteOrderQty' => false,
            ),
            'pro' => true, // 1200 req per min
            'rateLimit' => 50,
            'urls' => array(
                'api' => array(
                    'private' => 'https://api.binance.us/api/v3',
                    'public' => 'https://api.binance.us/api/v3',
                    'sapi' => 'https://api.binance.us/sapi/v1',
                    'sapiV2' => 'https://api.binance.us/sapi/v2',
                    'sapiV3' => 'https://api.binance.us/sapi/v3',
                    'web' => 'https://www.binance.us',
                ),
                'doc' => 'https://github.com/binance-us/binance-official-api-docs',
                'fees' => 'https://www.binance.us/en/fee/schedule',
                'logo' => 'https://github.com/user-attachments/assets/a9667919-b632-4d52-a832-df89f8a35e8c',
                'referral' => 'https://www.binance.us/?ref=35005074',
                'www' => 'https://www.binance.us',
            ),
            'features' => array(
                'swap' => array(
                    'linear' => null,
                    'inverse' => null,
                ),
                'future' => array(
                    'linear' => null,
                    'inverse' => null,
                ),
            ),
        ));
    }
}
