<?php

namespace ccxt\pro;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import

class binanceus extends \ccxt\pro\binance {

    public function describe(): mixed {
        // eslint-disable-next-line new-cap
        $restInstance = new \ccxt\async\binanceus ();
        $restDescribe = $restInstance->describe ();
        $parentWsDescribe = parent::describe_data();
        $extended = $this->deep_extend($restDescribe, $parentWsDescribe);
        return $this->deep_extend($extended, array(
            'certified' => false,
            'countries' => array( 'US' ),
            'fees' => array(
                'trading' => array(
                    'maker' => 0.0, // 0.1% trading fee, zero fees for all trading pairs before November 1
                    'percentage' => true,
                    'taker' => 0.0, // 0.1% trading fee, zero fees for all trading pairs before November 1
                    'tierBased' => false,
                ),
            ), // US
            'id' => 'binanceus',
            'name' => 'Binance US',
            'options' => array(
                'defaultType' => 'spot',
                'fetchCurrencies' => false,
                'fetchMarkets' => array( 'spot' ),
                'quoteOrderQty' => false,
            ),
            'urls' => array(
                'api' => array(
                    'private' => 'https://api.binance.us/api/v3',
                    'public' => 'https://api.binance.us/api/v3',
                    'sapi' => 'https://api.binance.us/sapi/v1',
                    'v1' => 'https://api.binance.us/api/v1',
                    'v3' => 'https://api.binance.us/api/v3',
                    'wapi' => 'https://api.binance.us/wapi/v3',
                    'web' => 'https://www.binance.us',
                    'ws' => array(
                        'spot' => 'wss://stream.binance.us:9443/ws',
                    ),
                ),
                'doc' => 'https://github.com/binance-us/binance-official-api-docs',
                'fees' => 'https://www.binance.us/en/fee/schedule',
                'logo' => 'https://user-images.githubusercontent.com/1294454/65177307-217b7c80-da5f-11e9-876e-0b748ba0a358.jpg',
                'referral' => 'https://www.binance.us/?ref=35005074',
                'www' => 'https://www.binance.us',
            ),
        ));
    }
}
